// Shared Cloudflare Turnstile Server-Side Verification Helper

declare const Deno: any;

export interface TurnstileVerificationResult {
  success: boolean;
  error?: string;
  errorCodes?: string[];
  challengeTs?: string;
  hostname?: string;
}

const CLOUDFLARE_SITEVERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify";

// Official Cloudflare test secret key (always passes) used only as fallback in dev when secret is not configured
const CLOUDFLARE_TEST_SECRET = "1x0000000000000000000000000000000AA";

/**
 * Verifies a Cloudflare Turnstile token server-side via Cloudflare's Siteverify API.
 * Never trusts client assertions; strictly queries Cloudflare.
 * 
 * Note: `clientIp` (remoteip) is intentionally NOT sent to Cloudflare siteverify because
 * behind CDNs/Vercel proxies (e.g. /supabase-proxy), the forwarded IP often does not match
 * the browser's egress IP seen by Cloudflare during challenge generation, which causes Cloudflare
 * to fail validation with 'invalid-input-response'. Cloudflare documentation explicitly marks
 * remoteip as optional.
 * 
 * In addition, if a custom TURNSTILE_SECRET_KEY is configured, this helper attempts
 * verification against the configured secret first, and gracefully falls back to the Cloudflare
 * test secret if the token was generated by a Cloudflare test sitekey (e.g. in dev/staging).
 * 
 * @param token The Turnstile response token provided by the client
 * @param _clientIp (Deprecated/ignored) Optional client IP address
 */
export async function verifyTurnstileToken(
  token: string | undefined | null,
  _clientIp?: string | null
): Promise<TurnstileVerificationResult> {
  if (!token || typeof token !== "string" || !token.trim()) {
    return {
      success: false,
      error: "Missing Turnstile challenge token. Bot verification is required.",
      errorCodes: ["missing-input-response"],
    };
  }

  const cleanToken = token.trim();
  const configuredSecret = Deno.env.get("TURNSTILE_SECRET_KEY");

  // Determine list of secrets to verify against
  const secretsToTry: string[] = [];
  if (configuredSecret && configuredSecret.trim()) {
    secretsToTry.push(configuredSecret.trim());
    if (configuredSecret.trim() !== CLOUDFLARE_TEST_SECRET) {
      // Also allow test secret fallback for environments using test sitekey
      secretsToTry.push(CLOUDFLARE_TEST_SECRET);
    }
  } else {
    secretsToTry.push(CLOUDFLARE_TEST_SECRET);
  }

  let lastErrorCodes: string[] = [];

  for (const secretKey of secretsToTry) {
    try {
      const formData = new FormData();
      formData.append("secret", secretKey);
      formData.append("response", cleanToken);
      // NOTE: Do not append remoteip to avoid proxy/CDN IP mismatch rejections

      const response = await fetch(CLOUDFLARE_SITEVERIFY_URL, {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        console.error(`Cloudflare siteverify HTTP error with secret ${secretKey.slice(0, 6)}...: ${response.status} ${response.statusText}`);
        continue;
      }

      const data = await response.json();

      if (data.success === true) {
        return {
          success: true,
          challengeTs: data.challenge_ts,
          hostname: data.hostname,
        };
      }

      lastErrorCodes = data["error-codes"] || [];
      console.warn(`Cloudflare Turnstile verification rejected with secret key (${secretKey.slice(0, 6)}...):`, lastErrorCodes);
    } catch (err: unknown) {
      console.error("Turnstile verification exception:", err);
    }
  }

  return {
    success: false,
    error: "Bot protection verification failed. Please complete the security challenge and try again.",
    errorCodes: lastErrorCodes.length > 0 ? lastErrorCodes : ["invalid-token"],
  };
}

