/**
 * Centralized SEO Configuration
 * Single Source of Truth for Route Metadata, Canonical URLs, and Open Graph tags.
 * Production Domain: https://www.shareholdervoting.in
 */

export const SITE_URL = 'https://www.shareholdervoting.in';

export interface RouteSEOConfig {
  title: string;
  description: string;
  canonical: string;
  h1: string;
  robots?: string;
  ogType?: string;
  ogImage?: string;
  contentUpdatedAt: string; // YYYY-MM-DD representing last substantial content revision
}

export const SEO_CONFIG: Record<string, RouteSEOConfig> = {
  '/': {
    title: 'Shareholder E-Voting Platform for AGMs & EGMs | Vote India Secure',
    description: 'Secure corporate voting software for Annual General Meetings (AGM), EGMs, and postal ballots with cryptographic ballot integrity and independent scrutinizer reporting.',
    canonical: `${SITE_URL}/`,
    h1: 'Shareholder E-Voting Platform for Companies',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/shareholder-e-voting': {
    title: 'Shareholder E-Voting Software | Vote India Secure',
    description: 'Enterprise shareholder electronic voting software with OTP authentication, weighted share representation, and cryptographic ballot verification.',
    canonical: `${SITE_URL}/shareholder-e-voting`,
    h1: 'Shareholder E-Voting Software',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/agm-voting': {
    title: 'AGM E-Voting Platform for Companies | Vote India Secure',
    description: 'Annual General Meeting (AGM) e-voting platform supporting remote pre-AGM voting, statutory ordinary and special business resolutions, and Form MGT-13 aligned exports.',
    canonical: `${SITE_URL}/agm-voting`,
    h1: 'AGM E-Voting Platform for Companies',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/egm-voting': {
    title: 'EGM E-Voting Platform for Companies | Vote India Secure',
    description: 'Extraordinary General Meeting (EGM) e-voting platform for urgent special resolutions, Section 100 requisitions, and statutory shareholder voting workflows.',
    canonical: `${SITE_URL}/egm-voting`,
    h1: 'Extraordinary General Meeting E-Voting Platform',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/corporate-voting': {
    title: 'Corporate Voting Software & Governance Solutions | Vote India Secure',
    description: 'Corporate voting software designed for board elections, member resolutions, and institutional governance with tamper-evident audit logging.',
    canonical: `${SITE_URL}/corporate-voting`,
    h1: 'Corporate Voting Software & Governance Solutions',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/proxy-voting': {
    title: 'Corporate Proxy Voting Software | Vote India Secure',
    description: 'Digital corporate proxy voting software supporting Section 105 proxy appointments, Form MGT-11 record keeping, and dual-voting prevention.',
    canonical: `${SITE_URL}/proxy-voting`,
    h1: 'Corporate Proxy Voting Software',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/scrutinizer-tools': {
    title: 'Scrutinizer Voting Reports & Audit Tools | Vote India Secure',
    description: 'Independent scrutinizer portal for general meetings featuring dual-witness digital unblocking, cryptographic ballot verification, and Form MGT-13 aligned report exports.',
    canonical: `${SITE_URL}/scrutinizer-tools`,
    h1: 'Scrutinizer Voting Reports & Audit Tools',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/security': {
    title: 'Shareholder Voting Security | Vote India Secure',
    description: 'Transparent security architecture: SHA-256 ballot hashing, Merkle audit trees, PostgreSQL Row-Level Security, TLS 1.3 encryption, and secret ballot preservation.',
    canonical: `${SITE_URL}/security`,
    h1: 'Shareholder Voting Security Architecture',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/pricing': {
    title: 'Corporate Voting Software Pricing | Vote India Secure',
    description: 'Transparent pricing for corporate voting software. Tiered solutions for small enterprises, growing companies, and large corporate general meetings.',
    canonical: `${SITE_URL}/pricing`,
    h1: 'Corporate Voting Software Pricing',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/about': {
    title: 'About Vote India Secure | Corporate Governance Platform',
    description: 'Learn about Vote India Secure: our engineering mission, transparent corporate governance technology, and independent software architecture.',
    canonical: `${SITE_URL}/about`,
    h1: 'About Vote India Secure',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/contact': {
    title: 'Contact Governance Support | Vote India Secure',
    description: 'Get in touch with the Vote India Secure corporate governance and technical team for event configuration, demonstrations, and platform inquiries.',
    canonical: `${SITE_URL}/contact`,
    h1: 'Contact Governance & Technology Support',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/regulatory-framework': {
    title: 'Electronic Voting Regulatory Framework | Vote India Secure',
    description: 'Overview of how platform technical workflows map to Section 108 of the Companies Act 2013 and Rule 20 requirements for general meeting voting.',
    canonical: `${SITE_URL}/regulatory-framework`,
    h1: 'Electronic Voting Regulatory Framework',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/data-protection': {
    title: 'Data Protection & Governance Architecture | Vote India Secure',
    description: 'Shareholder data protection standards, data localisation, encrypted storage at rest, and governance policies adhering to applicable privacy principles.',
    canonical: `${SITE_URL}/data-protection`,
    h1: 'Data Protection & Governance Architecture',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/features': {
    title: 'Enterprise Voting Platform Capabilities | Vote India Secure',
    description: 'Comprehensive platform capabilities: weighted voting calculations, real-time quorum monitoring, mobile responsiveness, and scrutinizer audit exports.',
    canonical: `${SITE_URL}/features`,
    h1: 'Enterprise Voting Platform Capabilities',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/how-it-works': {
    title: 'How Corporate E-Voting Works | Vote India Secure',
    description: 'Step-by-step breakdown of the electronic voting process from roster ingestion and 2FA authentication to ballot submission and scrutinizer verification.',
    canonical: `${SITE_URL}/how-it-works`,
    h1: 'How Corporate E-Voting Works',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/faqs': {
    title: 'Frequently Asked Questions | Vote India Secure',
    description: 'Answers to common questions regarding corporate general meetings, electronic balloting rules, quorum requirements, and scrutinizer procedures.',
    canonical: `${SITE_URL}/faqs`,
    h1: 'Frequently Asked Questions',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources': {
    title: 'Shareholder E-Voting Resources & Guides | Vote India Secure',
    description: 'Statutory guides, operational walkthroughs, and legal analyses for corporate secretarial teams, scrutinizers, and institutional shareholders.',
    canonical: `${SITE_URL}/resources`,
    h1: 'Statutory E-Voting Knowledge Base & Resources',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources/what-is-shareholder-e-voting': {
    title: 'What is Shareholder E-Voting? Statutory Guide | Vote India Secure',
    description: 'Comprehensive primer on electronic voting under Companies Act Section 108: legal mandate, physical vs remote comparison, and benefits.',
    canonical: `${SITE_URL}/resources/what-is-shareholder-e-voting`,
    h1: 'What is Shareholder E-Voting?',
    ogType: 'article',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources/how-agm-e-voting-works': {
    title: 'How AGM E-Voting Works Under Section 108 | Vote India Secure',
    description: 'Detailed operational timeline for Annual General Meetings: 21 clear days notice, remote voting window, venue balloting, and quorum.',
    canonical: `${SITE_URL}/resources/how-agm-e-voting-works`,
    h1: 'How AGM E-Voting Works Under Section 108',
    ogType: 'article',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources/how-egm-e-voting-works': {
    title: 'How EGM E-Voting Works Under Section 100 | Vote India Secure',
    description: 'Statutory procedure for Extraordinary General Meetings: Board requisitions, member requisitions under Section 100, and short notice provisions.',
    canonical: `${SITE_URL}/resources/how-egm-e-voting-works`,
    h1: 'How EGM E-Voting Works Under Section 100',
    ogType: 'article',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources/how-proxy-voting-works': {
    title: 'How Corporate Proxy Voting Works Under Section 105 | Vote India Secure',
    description: 'Legal rights and technical mechanisms of proxy voting under Companies Act Section 105: Form MGT-11 appointment and entitlement limits.',
    canonical: `${SITE_URL}/resources/how-proxy-voting-works`,
    h1: 'How Corporate Proxy Voting Works Under Section 105',
    ogType: 'article',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources/record-date-and-voting-entitlement': {
    title: 'Record Date & Voting Entitlement Mechanics | Vote India Secure',
    description: 'Analysis of cut-off date determination under Rule 20(4)(vii), depository registry coordination, and weighted shareholding calculations.',
    canonical: `${SITE_URL}/resources/record-date-and-voting-entitlement`,
    h1: 'Record Date & Voting Entitlement Mechanics',
    ogType: 'article',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources/ordinary-vs-special-resolution': {
    title: 'Ordinary vs Special Resolutions Under Section 114 | Vote India Secure',
    description: 'Statutory formulas and procedural differences between Ordinary and Special Resolutions under Section 114 of the Companies Act 2013.',
    canonical: `${SITE_URL}/resources/ordinary-vs-special-resolution`,
    h1: 'Ordinary vs Special Resolutions Under Section 114',
    ogType: 'article',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/resources/scrutinizer-voting-workflow': {
    title: 'Independent Scrutinizer Voting Workflow | Vote India Secure',
    description: 'Role of the scrutinizer under Rule 20(4)(ix): unblocking votes before two witnesses, register maintenance, and Form MGT-13 aligned reporting.',
    canonical: `${SITE_URL}/resources/scrutinizer-voting-workflow`,
    h1: 'Independent Scrutinizer Voting Workflow',
    ogType: 'article',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-09-20',
  },
  '/privacy-policy': {
    title: 'Privacy Policy | Vote India Secure',
    description: 'Privacy policy and data governance practices for shareholder e-voting and corporate meeting administration.',
    canonical: `${SITE_URL}/privacy-policy`,
    h1: 'Privacy Policy',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-08-01',
  },
  '/terms-of-service': {
    title: 'Terms of Service | Vote India Secure',
    description: 'Terms of service governing use of the Vote India Secure platform for corporate voting events and governance administration.',
    canonical: `${SITE_URL}/terms-of-service`,
    h1: 'Terms of Service',
    ogType: 'website',
    ogImage: `${SITE_URL}/og-image.jpg`,
    contentUpdatedAt: '2026-08-01',
  },
};
